// Currency data (subset kept for brevity if needed; full list recommended)
// Using the same dataset from c.html
window.currencyData = [
  { country: "Afghanistan", currencyName: "Afghan afghani", code: "AFN (؋)" },
  { country: "Albania", currencyName: "Albanian lek", code: "ALL (L)" },
  { country: "Algeria", currencyName: "Algerian dinar", code: "DZD (د.ج)" },
  { country: "Andorra", currencyName: "Euro", code: "EUR (€)" },
  { country: "Angola", currencyName: "Angolan kwanza", code: "AOA (Kz)" },
  { country: "Antigua and Barbuda", currencyName: "East Caribbean dollar", code: "XCD ($)" },
  { country: "Argentina", currencyName: "Argentine peso", code: "ARS ($)" },
  { country: "Armenia", currencyName: "Armenian dram", code: "AMD (֏)" },
  { country: "Australia", currencyName: "Australian dollar", code: "AUD ($)" },
  { country: "Austria", currencyName: "Euro", code: "EUR (€)" },
  { country: "Belgium", currencyName: "Euro", code: "EUR (€)" },
  { country: "Brazil", currencyName: "Brazilian real", code: "BRL (R$)" },
  { country: "Canada", currencyName: "Canadian dollar", code: "CAD ($)" },
  { country: "China", currencyName: "Chinese yuan (Renminbi)", code: "CNY (¥)" },
  { country: "Croatia", currencyName: "Euro", code: "EUR (€)" },
  { country: "Czech Republic", currencyName: "Czech koruna", code: "CZK (Kč)" },
  { country: "Denmark", currencyName: "Danish krone", code: "DKK (kr)" },
  { country: "Egypt", currencyName: "Egyptian pound", code: "EGP (£)" },
  { country: "Finland", currencyName: "Euro", code: "EUR (€)" },
  { country: "France", currencyName: "Euro", code: "EUR (€)" },
  { country: "Germany", currencyName: "Euro", code: "EUR (€)" },
  { country: "Greece", currencyName: "Euro", code: "EUR (€)" },
  { country: "Hong Kong", currencyName: "Hong Kong dollar", code: "HKD ($)" },
  { country: "Hungary", currencyName: "Hungarian forint", code: "HUF (Ft)" },
  { country: "India", currencyName: "Indian rupee", code: "INR (₹)" },
  { country: "Indonesia", currencyName: "Indonesian rupiah", code: "IDR (Rp)" },
  { country: "Ireland", currencyName: "Euro", code: "EUR (€)" },
  { country: "Israel", currencyName: "Israeli new shekel", code: "ILS (₪)" },
  { country: "Italy", currencyName: "Euro", code: "EUR (€)" },
  { country: "Japan", currencyName: "Japanese yen", code: "JPY (¥)" },
  { country: "Kenya", currencyName: "Kenyan shilling", code: "KES (Sh)" },
  { country: "Mexico", currencyName: "Mexican peso", code: "MXN ($)" },
  { country: "Netherlands", currencyName: "Euro", code: "EUR (€)" },
  { country: "New Zealand", currencyName: "New Zealand dollar", code: "NZD ($)" },
  { country: "Norway", currencyName: "Norwegian krone", code: "NOK (kr)" },
  { country: "Poland", currencyName: "Polish złoty", code: "PLN (zł)" },
  { country: "Portugal", currencyName: "Euro", code: "EUR (€)" },
  { country: "Romania", currencyName: "Romanian leu", code: "RON (lei)" },
  { country: "Russia", currencyName: "Russian ruble", code: "RUB (₽)" },
  { country: "Saudi Arabia", currencyName: "Saudi riyal", code: "SAR (﷼)" },
  { country: "Singapore", currencyName: "Singapore dollar", code: "SGD ($)" },
  { country: "South Africa", currencyName: "South African rand", code: "ZAR (R)" },
  { country: "South Korea", currencyName: "South Korean won", code: "KRW (₩)" },
  { country: "Spain", currencyName: "Euro", code: "EUR (€)" },
  { country: "Sweden", currencyName: "Swedish krona", code: "SEK (kr)" },
  { country: "Switzerland", currencyName: "Swiss franc", code: "CHF (Fr)" },
  { country: "Thailand", currencyName: "Thai baht", code: "THB (฿)" },
  { country: "Turkey", currencyName: "Turkish lira", code: "TRY (₺)" },
  { country: "United Arab Emirates", currencyName: "UAE dirham", code: "AED (د.إ)" },
  { country: "United Kingdom", currencyName: "Pound sterling", code: "GBP (£)" },
  { country: "United States", currencyName: "United States dollar", code: "USD ($)" },
  { country: "Vietnam", currencyName: "Vietnamese đồng", code: "VND (₫)" },
  { country: "Zimbabwe", currencyName: "Zimbabwean dollar", code: "ZWL ($)" }
];

